filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/services/user-service/*.log
      - /var/log/services/event-service/*.log
      - /var/log/services/booking-service/*.log
      - /var/log/services/payment-service/*.log
      - /var/log/services/notification-service/*.log
      - /var/log/services/api-gateway/*.log
    json.keys_under_root: true
    json.add_error_key: true

output.kafka:
  hosts: ["kafka:9092"]
  topic: "filebeat-logs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
