global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ticket-booking-platform'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8081']
    metrics_path: '/metrics'

  - job_name: 'event-service'
    static_configs:
      - targets: ['event-service:8082']
    metrics_path: '/metrics'

  - job_name: 'booking-service'
    static_configs:
      - targets: ['booking-service:8083']
    metrics_path: '/metrics'

  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment-service:8084']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']
    metrics_path: '/metrics'

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
    metrics_path: '/metrics'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []
