// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: proto/booking/booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShowId        int64                  `protobuf:"varint,3,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,4,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_proto_booking_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *Booking) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Booking) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Booking) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShowId        int64                  `protobuf:"varint,3,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,4,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_proto_booking_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Reservation) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *Reservation) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

func (x *Reservation) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ReserveSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ShowId        int64                  `protobuf:"varint,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,3,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatRequest) Reset() {
	*x = ReserveSeatRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatRequest) ProtoMessage() {}

func (x *ReserveSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatRequest.ProtoReflect.Descriptor instead.
func (*ReserveSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveSeatRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReserveSeatRequest) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *ReserveSeatRequest) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type ReserveSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ReservationId string                 `protobuf:"bytes,3,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveSeatResponse) Reset() {
	*x = ReserveSeatResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveSeatResponse) ProtoMessage() {}

func (x *ReserveSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveSeatResponse.ProtoReflect.Descriptor instead.
func (*ReserveSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{3}
}

func (x *ReserveSeatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReserveSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ReserveSeatResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReserveSeatResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type ConfirmBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PaymentId     string                 `protobuf:"bytes,3,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingRequest) Reset() {
	*x = ConfirmBookingRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingRequest) ProtoMessage() {}

func (x *ConfirmBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingRequest.ProtoReflect.Descriptor instead.
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmBookingRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ConfirmBookingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConfirmBookingRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type ConfirmBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Booking       *Booking               `protobuf:"bytes,3,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmBookingResponse) Reset() {
	*x = ConfirmBookingResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmBookingResponse) ProtoMessage() {}

func (x *ConfirmBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmBookingResponse.ProtoReflect.Descriptor instead.
func (*ConfirmBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmBookingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ConfirmBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConfirmBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CancelBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingRequest) Reset() {
	*x = CancelBookingRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingRequest) ProtoMessage() {}

func (x *CancelBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingRequest.ProtoReflect.Descriptor instead.
func (*CancelBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{6}
}

func (x *CancelBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *CancelBookingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CancelBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelBookingResponse) Reset() {
	*x = CancelBookingResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelBookingResponse) ProtoMessage() {}

func (x *CancelBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelBookingResponse.ProtoReflect.Descriptor instead.
func (*CancelBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{7}
}

func (x *CancelBookingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CancelBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequest) Reset() {
	*x = GetBookingRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequest) ProtoMessage() {}

func (x *GetBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{8}
}

func (x *GetBookingRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *GetBookingRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Booking       *Booking               `protobuf:"bytes,3,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingResponse) Reset() {
	*x = GetBookingResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingResponse) ProtoMessage() {}

func (x *GetBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingResponse.ProtoReflect.Descriptor instead.
func (*GetBookingResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{9}
}

func (x *GetBookingResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBookingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetBookingResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type ListBookingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsRequest) Reset() {
	*x = ListBookingsRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsRequest) ProtoMessage() {}

func (x *ListBookingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{10}
}

func (x *ListBookingsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBookingsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBookingsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListBookingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Bookings      []*Booking             `protobuf:"bytes,3,rep,name=bookings,proto3" json:"bookings,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingsResponse) Reset() {
	*x = ListBookingsResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingsResponse) ProtoMessage() {}

func (x *ListBookingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingsResponse.ProtoReflect.Descriptor instead.
func (*ListBookingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{11}
}

func (x *ListBookingsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListBookingsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListBookingsResponse) GetBookings() []*Booking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

func (x *ListBookingsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ReleaseSeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	ShowId        int64                  `protobuf:"varint,2,opt,name=show_id,json=showId,proto3" json:"show_id,omitempty"`
	SeatIds       []int64                `protobuf:"varint,3,rep,packed,name=seat_ids,json=seatIds,proto3" json:"seat_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatRequest) Reset() {
	*x = ReleaseSeatRequest{}
	mi := &file_proto_booking_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatRequest) ProtoMessage() {}

func (x *ReleaseSeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatRequest.ProtoReflect.Descriptor instead.
func (*ReleaseSeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseSeatRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *ReleaseSeatRequest) GetShowId() int64 {
	if x != nil {
		return x.ShowId
	}
	return 0
}

func (x *ReleaseSeatRequest) GetSeatIds() []int64 {
	if x != nil {
		return x.SeatIds
	}
	return nil
}

type ReleaseSeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatResponse) Reset() {
	*x = ReleaseSeatResponse{}
	mi := &file_proto_booking_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatResponse) ProtoMessage() {}

func (x *ReleaseSeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_booking_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatResponse.ProtoReflect.Descriptor instead.
func (*ReleaseSeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_booking_booking_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseSeatResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ReleaseSeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_booking_booking_proto protoreflect.FileDescriptor

const file_proto_booking_booking_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/booking/booking.proto\x12\abooking\"\xdf\x01\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\ashow_id\x18\x03 \x01(\x03R\x06showId\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\x03R\aseatIds\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\x03R\texpiresAt\"\x89\x01\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x17\n" +
	"\ashow_id\x18\x03 \x01(\x03R\x06showId\x12\x19\n" +
	"\bseat_ids\x18\x04 \x03(\x03R\aseatIds\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\x03R\texpiresAt\"a\n" +
	"\x12ReserveSeatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\x03R\x06showId\x12\x19\n" +
	"\bseat_ids\x18\x03 \x03(\x03R\aseatIds\"\x89\x01\n" +
	"\x13ReserveSeatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0ereservation_id\x18\x03 \x01(\tR\rreservationId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\"v\n" +
	"\x15ConfirmBookingRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x03 \x01(\tR\tpaymentId\"r\n" +
	"\x16ConfirmBookingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\abooking\x18\x03 \x01(\v2\x10.booking.BookingR\abooking\"N\n" +
	"\x14CancelBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"E\n" +
	"\x15CancelBookingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"K\n" +
	"\x11GetBookingRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"n\n" +
	"\x12GetBookingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\abooking\x18\x03 \x01(\v2\x10.booking.BookingR\abooking\"_\n" +
	"\x13ListBookingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x88\x01\n" +
	"\x14ListBookingsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\bbookings\x18\x03 \x03(\v2\x10.booking.BookingR\bbookings\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"o\n" +
	"\x12ReleaseSeatRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\ashow_id\x18\x02 \x01(\x03R\x06showId\x12\x19\n" +
	"\bseat_ids\x18\x03 \x03(\x03R\aseatIds\"C\n" +
	"\x13ReleaseSeatResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xdd\x03\n" +
	"\x0eBookingService\x12I\n" +
	"\fReserveSeats\x12\x1b.booking.ReserveSeatRequest\x1a\x1c.booking.ReserveSeatResponse\x12Q\n" +
	"\x0eConfirmBooking\x12\x1e.booking.ConfirmBookingRequest\x1a\x1f.booking.ConfirmBookingResponse\x12N\n" +
	"\rCancelBooking\x12\x1d.booking.CancelBookingRequest\x1a\x1e.booking.CancelBookingResponse\x12E\n" +
	"\n" +
	"GetBooking\x12\x1a.booking.GetBookingRequest\x1a\x1b.booking.GetBookingResponse\x12K\n" +
	"\fListBookings\x12\x1c.booking.ListBookingsRequest\x1a\x1d.booking.ListBookingsResponse\x12I\n" +
	"\fReleaseSeats\x12\x1b.booking.ReleaseSeatRequest\x1a\x1c.booking.ReleaseSeatResponseB\vZ\t./bookingb\x06proto3"

var (
	file_proto_booking_booking_proto_rawDescOnce sync.Once
	file_proto_booking_booking_proto_rawDescData []byte
)

func file_proto_booking_booking_proto_rawDescGZIP() []byte {
	file_proto_booking_booking_proto_rawDescOnce.Do(func() {
		file_proto_booking_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_booking_booking_proto_rawDesc), len(file_proto_booking_booking_proto_rawDesc)))
	})
	return file_proto_booking_booking_proto_rawDescData
}

var file_proto_booking_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_booking_booking_proto_goTypes = []any{
	(*Booking)(nil),                // 0: booking.Booking
	(*Reservation)(nil),            // 1: booking.Reservation
	(*ReserveSeatRequest)(nil),     // 2: booking.ReserveSeatRequest
	(*ReserveSeatResponse)(nil),    // 3: booking.ReserveSeatResponse
	(*ConfirmBookingRequest)(nil),  // 4: booking.ConfirmBookingRequest
	(*ConfirmBookingResponse)(nil), // 5: booking.ConfirmBookingResponse
	(*CancelBookingRequest)(nil),   // 6: booking.CancelBookingRequest
	(*CancelBookingResponse)(nil),  // 7: booking.CancelBookingResponse
	(*GetBookingRequest)(nil),      // 8: booking.GetBookingRequest
	(*GetBookingResponse)(nil),     // 9: booking.GetBookingResponse
	(*ListBookingsRequest)(nil),    // 10: booking.ListBookingsRequest
	(*ListBookingsResponse)(nil),   // 11: booking.ListBookingsResponse
	(*ReleaseSeatRequest)(nil),     // 12: booking.ReleaseSeatRequest
	(*ReleaseSeatResponse)(nil),    // 13: booking.ReleaseSeatResponse
}
var file_proto_booking_booking_proto_depIdxs = []int32{
	0,  // 0: booking.ConfirmBookingResponse.booking:type_name -> booking.Booking
	0,  // 1: booking.GetBookingResponse.booking:type_name -> booking.Booking
	0,  // 2: booking.ListBookingsResponse.bookings:type_name -> booking.Booking
	2,  // 3: booking.BookingService.ReserveSeats:input_type -> booking.ReserveSeatRequest
	4,  // 4: booking.BookingService.ConfirmBooking:input_type -> booking.ConfirmBookingRequest
	6,  // 5: booking.BookingService.CancelBooking:input_type -> booking.CancelBookingRequest
	8,  // 6: booking.BookingService.GetBooking:input_type -> booking.GetBookingRequest
	10, // 7: booking.BookingService.ListBookings:input_type -> booking.ListBookingsRequest
	12, // 8: booking.BookingService.ReleaseSeats:input_type -> booking.ReleaseSeatRequest
	3,  // 9: booking.BookingService.ReserveSeats:output_type -> booking.ReserveSeatResponse
	5,  // 10: booking.BookingService.ConfirmBooking:output_type -> booking.ConfirmBookingResponse
	7,  // 11: booking.BookingService.CancelBooking:output_type -> booking.CancelBookingResponse
	9,  // 12: booking.BookingService.GetBooking:output_type -> booking.GetBookingResponse
	11, // 13: booking.BookingService.ListBookings:output_type -> booking.ListBookingsResponse
	13, // 14: booking.BookingService.ReleaseSeats:output_type -> booking.ReleaseSeatResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_booking_booking_proto_init() }
func file_proto_booking_booking_proto_init() {
	if File_proto_booking_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_booking_booking_proto_rawDesc), len(file_proto_booking_booking_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_booking_booking_proto_goTypes,
		DependencyIndexes: file_proto_booking_booking_proto_depIdxs,
		MessageInfos:      file_proto_booking_booking_proto_msgTypes,
	}.Build()
	File_proto_booking_booking_proto = out.File
	file_proto_booking_booking_proto_goTypes = nil
	file_proto_booking_booking_proto_depIdxs = nil
}
